# Generated by Django 3.2.3 on 2021-06-18 21:29

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=localflavor.br.models.BRStateField(default=1, max_length=2, verbose_name='Estado UF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='CNPJ',
            field=localflavor.br.models.BRCNPJField(max_length=18, unique=True, verbose_name='Número CPF'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Selecione', max_length=25),
        ),
    ]
