# Generated by Django 3.2 on 2021-05-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_bp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentesco',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Obs.'),
        ),
    ]
