# Generated by Django 3.2.3 on 2021-06-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_bp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentesco',
            name='anexo_doc_nascimento',
            field=models.ImageField(blank=True, null=True, upload_to='anexo_parentesco_nascimento'),
        ),
    ]
