# Generated by Django 3.2.3 on 2021-06-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_bp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentesco',
            name='status',
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='declaracao_saude',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Nao')], default='Selecione', max_length=25),
        ),
    ]
