# Generated by Django 3.2 on 2021-05-03 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_at', '0002_alter_titular_observacoes'),
        ('cad_bp', '0002_alter_parentesco_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentesco',
            name='titular',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cad_at.titular'),
        ),
    ]
