# Generated by Django 3.2.3 on 2021-06-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_bp', '0002_parentesco_anexo_doc_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentesco',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('Sem Prioridade', 'Sem Prioridade'), ('Recem Nascido', 'Recem Nascido'), ('Recem Casado', 'Casado(a)')], default='Selecione', max_length=25),
        ),
    ]
