# Generated by Django 3.2 on 2021-05-03 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_at', '0002_alter_titular_observacoes'),
        ('cad_bp', '0003_alter_parentesco_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentesco',
            name='titular',
            field=models.ForeignKey(default='Selecione', on_delete=django.db.models.deletion.CASCADE, to='cad_at.titular'),
        ),
    ]
