# Generated by Django 3.2 on 2021-05-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_bp', '0004_alter_parentesco_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentesco',
            name='data_admissao',
            field=models.DateField(verbose_name='Data Admissiao'),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='data_recebimento',
            field=models.DateField(verbose_name='Data Recebimento'),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Convivente', 'Convivente')], default='Selecione', max_length=25),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Selecione', max_length=25),
        ),
    ]
