# Generated by Django 3.2.2 on 2021-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_bp', '0005_auto_20210502_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentesco',
            name='anexo_doc_parentesco',
            field=models.ImageField(default=1, upload_to='anexo_doc_parentesco'),
            preserve_default=False,
        ),
    ]
