# Generated by Django 3.2.2 on 2021-05-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_bp', '0007_alter_parentesco_anexo_doc_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentesco',
            name='data_admissao',
            field=models.DateField(verbose_name='Data de Admissão'),
        ),
    ]
