# Generated by Django 3.2.2 on 2021-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_bp', '0008_alter_parentesco_data_admissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentesco',
            name='anexo_doc_parentesco',
            field=models.ImageField(blank=True, null=True, upload_to='parentesco'),
        ),
    ]
