# Generated by Django 3.2.2 on 2021-05-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_bp', '0009_alter_parentesco_anexo_doc_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentesco',
            name='anexo_doc_parentesco',
            field=models.ImageField(blank=True, null=True, upload_to='cad_bp'),
        ),
    ]
