# Generated by Django 3.2.3 on 2021-05-28 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cad_emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNPJ', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('cod_empresa', models.CharField(max_length=25, unique=True, verbose_name='Codigo Empresa')),
                ('data_recebimento', models.DateField(blank=True, verbose_name='Data Recebimento')),
                ('tipo_contrato', models.CharField(default='Inclusão de Titular', editable=False, max_length=25, verbose_name='Tipo Cadastro')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('anexo_doc_emp', models.ImageField(blank=True, null=True, upload_to='anexo_empresa')),
                ('vencimento_boleto', models.DateField(verbose_name='Vencimento do Boleto')),
                ('inicio_vigencia', models.DateField(verbose_name='Inicio de Vigência')),
                ('historico_reajuste', models.CharField(max_length=100, null=True, verbose_name='Histórico de Reajuste')),
                ('historico_sinistro', models.CharField(max_length=100, null=True, verbose_name='Histórico de Sinistralidade')),
                ('declaracao_saude', models.CharField(max_length=255, verbose_name='Declaracao Saude')),
                ('status', models.CharField(default='OK', editable=False, max_length=25, verbose_name='Status')),
                ('cod_apolice', models.CharField(max_length=255, verbose_name='Código ou Apólice')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs.')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('empresa_principal', models.ForeignKey(default='Selecione', on_delete=django.db.models.deletion.CASCADE, to='cad_emp.empresa')),
            ],
        ),
    ]
