# Generated by Django 3.2 on 2021-04-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'Fazendo'), ('done', 'Feito')], max_length=5),
        ),
    ]
