# Generated by Django 3.2 on 2021-05-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11, verbose_name='CPF')),
                ('cod_empresa', models.CharField(max_length=25, verbose_name='Codigo Empresa')),
                ('data_recebimento', models.DateField(blank=True, verbose_name='Data Recebimento')),
                ('tipo', models.CharField(default='Inclusão de Titular', editable=False, max_length=25, verbose_name='Tipo Cadastro')),
                ('nome_benef', models.CharField(max_length=255, verbose_name='Nome Beneficiario')),
                ('data_nascimento', models.DateField(blank=True, verbose_name='Data Nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Selecione', max_length=25)),
                ('estado_civil', models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Convivente', 'Convivente')], default='Selecione', max_length=25)),
                ('nome_mae', models.CharField(max_length=255, verbose_name='Nome da Mae')),
                ('data_admissao', models.DateField(blank=True, verbose_name='Data Admissiao')),
                ('tipo_parentesco', models.CharField(default='Sem Parentesco', editable=False, max_length=25, verbose_name='Tipo Parentesco')),
                ('celular', models.CharField(max_length=100, null=True, verbose_name='Numero do Celular')),
                ('cidade', models.CharField(max_length=150, verbose_name='Cidade')),
                ('declaracao_saude', models.CharField(max_length=255, verbose_name='Declaracao Saude')),
                ('status', models.CharField(default='OK', editable=False, max_length=25, verbose_name='Status')),
                ('desc_declarao_saude', models.CharField(max_length=255, verbose_name='Desc. Declaracao Saude')),
                ('observacoes', models.TextField(null=True, verbose_name='Obs.')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
            ],
        ),
    ]
