# Generated by Django 3.2.3 on 2021-05-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_at', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titular',
            name='carteirinha',
            field=models.CharField(max_length=35, unique=True, verbose_name='Numero da Carteirinha'),
        ),
    ]
