# Generated by Django 3.2 on 2021-05-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_at', '0002_alter_titular_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titular',
            name='data_admissao',
            field=models.DateField(verbose_name='Data Admissiao'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Convivente', 'Convivente')], default='Selecione', max_length=25),
        ),
    ]
