# Generated by Django 3.2.2 on 2021-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_at', '0003_auto_20210502_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='titular',
            name='anexo_doc_tit',
            field=models.ImageField(default=1, upload_to='anexo_doc_tit'),
            preserve_default=False,
        ),
    ]
