# Generated by Django 3.2.2 on 2021-05-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_at', '0004_titular_anexo_doc_tit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titular',
            name='anexo_doc_tit',
            field=models.ImageField(blank=True, null=True, upload_to='anexo_doc_tit'),
        ),
    ]
