# Generated by Django 3.2.2 on 2021-05-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_at', '0005_alter_titular_anexo_doc_tit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titular',
            name='data_admissao',
            field=models.DateField(verbose_name='Data de Admissao'),
        ),
    ]
