# Generated by Django 3.2 on 2021-05-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefa',
            new_name='Registros',
        ),
    ]
