# Generated by Django 3.2 on 2021-05-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_rename_tarefa_registros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registros',
            new_name='Registro',
        ),
    ]
