# Generated by Django 3.2.2 on 2021-05-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_rename_registros_registro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='Tarefa',
        ),
    ]
